### ISSUE TITLE
Fail2Ban does not work on Debian 12 due to the absence of catalina.out

### ISSUE THREAD

**Issue by sovaru25** [itiligent/Easy-Guacamole-Installer#69]
**Problem Description:**
When setting up Fail2Ban on Debian 12, an issue arises: Fail2Ban cannot function correctly because the catalina.out file is missing in the /var/log/tomcat9/ directory. Instead, Tomcat logs are written to files with dates, such as catalina.2024-XX-XX.log.

**Cause of the Problem:**
In Debian 12, the logging configuration for Tomcat has changed

**Solution:**
To revert Tomcat logging to the catalina.out file, you need to modify the system logging configuration. Here are the steps to achieve this:

**Edit the Tomcat service file:**
Open the /usr/lib/systemd/system/tomcat9.service file for editing:
sudo nano /usr/lib/systemd/system/tomcat9.service

**Modify the logging configuration:**
Add the following lines to the # Logging [Service] section:
StandardOutput=append:/var/log/tomcat9/catalina.out
StandardError=append:/var/log/tomcat9/catalina.out

**Restart the Tomcat service:**
sudo systemctl daemon-reload
sudo systemctl restart tomcat9

**Comment by itiligent** [comment]
I appreaciate your detail, its is very helpful. Thankyou! 

I want to confirm whether this is the same issue I addressed in commit 14495c3 from August 24 as Debian 12 does indeed do logs differently. 

Could you please check to that your fail2ban.conf file includes :
```
[sshd]
backend=systemd
enabled = true
````

if it did  include the above when you found this issue , somtehing additioal must have changed since August 24 when I last tested. If so I'll look to including your fix in the install script

thanks again

**Comment by sovaru25** [comment]
To confirm, I checked my jail.local file, and it includes the following settings:
> [sshd]
backend=systemd

However, the enabled = true line is not present in the jail.local file. 
Instead, the script you provided creates a temporary configuration file /tmp/fail2ban.conf with the following content:

> [DEFAULT]
destemail = yourname@example.com
sender = yourname@example.com
action = %(action_mwl)s
ignoreip =

> [sshd]
backend=systemd
enabled = true

This temporary configuration file is used during the installation process. Given that the enabled = true setting is included 
in the script but not directly in the jail.local file, it seems that something additional might have changed since your last test on August 24.

**Comment by itiligent** [comment]
I just noticed a typo with missong spaced.  backend=systemd should be 'backend = systemd' I wonder if this is the culprit?

**Comment by itiligent** [comment]
This is fixed now... it was quite a fiddly update, but working fine now.
